<?php

/**
 * @var \Hiberus\Roman\Block\Index $block
 */

$alumns= $block->getAlumn();
$marks = $block->averageMarks();
?>
<div>
<h2 class="title">NOTAS EXAM</h2>
    <div class="alumns">
    <button id="alerta">Highest Mark</button>
<?php
foreach ($alumns as $alumn){
    ?>
<ul>
    <li><b>Nombre:</b> <?= $alumn->getFirstname(); ?></li>
    <li><b>Apellido:</b> <?= $alumn->getLastname(); ?></li>
    <li id="mark"><b>Nota:</b> <?= $alumn->getMark(); ?></li>
</ul>
<?php } ?>
<p>Total number of students: <b><?= count($alumns) ?></b></p>
    </div>

    <div>
        <h3>Media de notas: <b><?= $marks ?></b></h3>
    </div>
</div>
