<?php

/**
 * @var \Hiberus\Roman\Block\Index $block
 */
//$block->addAlumn();
$alumns = $block->getAlumn();
$marks = $block->averageMarks();
$maxMarks=$block->getHighestMarks();
$minMark = $block->getMark();
$elements = $block->getElements();
$i = 0;

?>

<h2 class="title">NOTAS EXAM</h2>
<div class="btns">
    <!-- Se comprueba si hay elementos para poner los botones en disabled -->
    <?php
    if ($elements != 0){ ?>
    <button id="alerta">Highest Mark</button>
    <button id="btnDisplay">Show/Hide</button>
   <?php
    } else { ?>
        <button id="alerta" disabled>Highest Mark</button>
    <button id="btnDisplay" disabled>Show/Hide</button>
    <?php }
    ?>

</div>
<div id="alumns" class="alumns">

<?php
foreach ($alumns as $alumn)
{
    if ($i++ == $elements) break;
    if($alumn->getMark() > $minMark){
    $class = "pass";
    }else{
    $class = "notpass";
    } ?>
<ul>
    <li><b>Nombre:</b> <?= $alumn->getFirstname() ?></li>
    <li><b>Apellido:</b> <?= $alumn->getLasname() ?></li>
    <li id="mark" class="<?= $class ?>"><b>Nota:</b> <?= $alumn->getMark() ?></li>
</ul>
<?php } ?>
</div>
<p>Total number of students: <b><?= count($alumns) ?></b></p>


    <div>
        <h3>Media de notas: <b><?= $marks ?></b></h3>
    </div>

<script>
    let hMark = <?= $block->getHighestMark() ?>
</script>
<script>

    require(['jquery', 'alertHighestMark'], function($, alertHighestMark) {
        alertHighestMark('#alerta');
    });

    require(['jquery', 'btnDisplay'], function($, btndisplay) {
        btndisplay('#btnDisplay', '#alumns');
    });

</script>
